apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8sd
  template:
    metadata:
      labels:
        app: k8sd
    spec:
      containers:
        - name: k8sd
          image: barkurguru/k8sd
          ports:
            - containerPort: 8060